server.port=8081
spring.application.name=OcorrenciasEscolares
spring.jackson.property-naming-strategy=SNAKE_CASE

#MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DBN_URL}
spring.datasource.username=${DBN_USER}
spring.datasource.password=${DBN_PASSWORD}

#JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
